-- DBTHON-26 baseline. Applied only by Alembic to the dedicated project database.
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='dbthon_runtime') THEN
    CREATE ROLE dbthon_runtime NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='dbthon_worker') THEN
    CREATE ROLE dbthon_worker NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='dbthon_auth') THEN
    CREATE ROLE dbthon_auth NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='dbthon_guard') THEN
    CREATE ROLE dbthon_guard NOLOGIN BYPASSRLS;
  END IF;
END $$;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO dbthon_runtime, dbthon_worker, dbthon_auth, dbthon_guard;

CREATE TABLE zones (
  zone_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_name varchar(60) NOT NULL, city varchar(60) NOT NULL,
  pincode_range varchar(20) NOT NULL, UNIQUE (city, zone_name)
);
CREATE TABLE users (
  user_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zone_id bigint NOT NULL REFERENCES zones,
  name varchar(100) NOT NULL, email varchar(100) UNIQUE NOT NULL,
  phone varchar(15) UNIQUE NOT NULL, password_hash text NOT NULL,
  latitude numeric(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude numeric(9,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  verified_status boolean NOT NULL DEFAULT false, active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (email=lower(trim(email))), CHECK (length(trim(name))>0)
);
CREATE INDEX ix_users_zone ON users(zone_id);
CREATE TABLE user_roles (
  user_id bigint REFERENCES users NOT NULL,
  role varchar(12) NOT NULL CHECK (role IN ('Donor','Receiver','Volunteer','Admin')),
  approved_at timestamptz, approved_by bigint REFERENCES users,
  PRIMARY KEY (user_id, role), CHECK ((approved_at IS NULL)=(approved_by IS NULL))
);
CREATE TABLE receiver_profiles (
  user_id bigint PRIMARY KEY REFERENCES users,
  capacity_kg numeric(8,2) NOT NULL CHECK (capacity_kg>0)
);
CREATE TABLE food_listings (
  listing_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_id bigint NOT NULL REFERENCES users, zone_id bigint NOT NULL REFERENCES zones,
  food_type varchar(80) NOT NULL CHECK (length(trim(food_type))>0),
  category varchar(10) NOT NULL CHECK (category IN ('Veg','NonVeg')),
  quantity_kg numeric(8,2) NOT NULL CHECK (quantity_kg>0),
  prepared_at timestamptz NOT NULL, expiry_window_start timestamptz NOT NULL,
  expiry_window_end timestamptz NOT NULL,
  pickup_lat numeric(9,6) NOT NULL CHECK (pickup_lat BETWEEN -90 AND 90),
  pickup_long numeric(9,6) NOT NULL CHECK (pickup_long BETWEEN -180 AND 180),
  pickup_location geography(Point,4326) GENERATED ALWAYS AS
    (ST_SetSRID(ST_MakePoint(pickup_long::float8,pickup_lat::float8),4326)::geography) STORED,
  status varchar(12) NOT NULL DEFAULT 'Available'
    CHECK (status IN ('Available','Claimed','PickedUp','Delivered','Expired','Cancelled')),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (prepared_at<=expiry_window_start AND expiry_window_start<expiry_window_end)
);
CREATE INDEX ix_listings_live_zone ON food_listings(zone_id,status,expiry_window_end);
CREATE INDEX ix_listings_pickup_gist ON food_listings USING gist(pickup_location);
CREATE INDEX ix_listings_donor ON food_listings(donor_id,created_at);
CREATE TABLE claims (
  claim_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id bigint NOT NULL REFERENCES food_listings, receiver_id bigint NOT NULL REFERENCES users,
  claimed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  status varchar(12) NOT NULL DEFAULT 'Confirmed'
    CHECK (status IN ('Confirmed','Cancelled','Expired','Completed')),
  ended_at timestamptz, cancellation_reason text,
  CHECK ((status='Confirmed')=(ended_at IS NULL)), CHECK (ended_at IS NULL OR ended_at>=claimed_at)
);
CREATE UNIQUE INDEX uq_claim_allocation ON claims(listing_id) WHERE status IN ('Confirmed','Completed');
CREATE INDEX ix_claims_listing ON claims(listing_id);
CREATE INDEX ix_claims_receiver ON claims(receiver_id,claimed_at);
CREATE TABLE pickups (
  claim_id bigint NOT NULL REFERENCES claims,
  pickup_id bigint GENERATED BY DEFAULT AS IDENTITY,
  volunteer_id bigint NOT NULL REFERENCES users, scheduled_time timestamptz NOT NULL,
  actual_pickup_time timestamptz, delivery_time timestamptz, ended_at timestamptz,
  status varchar(12) NOT NULL DEFAULT 'Scheduled'
    CHECK (status IN ('Scheduled','PickedUp','Delivered','Missed','Cancelled','Failed')),
  reason text, PRIMARY KEY (claim_id,pickup_id),
  CHECK ((status IN ('PickedUp','Delivered','Failed'))=(actual_pickup_time IS NOT NULL)),
  CHECK ((status='Delivered')=(delivery_time IS NOT NULL)),
  CHECK (delivery_time IS NULL OR delivery_time>=actual_pickup_time),
  CHECK ((status IN ('Delivered','Missed','Cancelled','Failed'))=(ended_at IS NOT NULL)),
  CHECK (ended_at IS NULL OR actual_pickup_time IS NULL OR ended_at>=actual_pickup_time)
);
CREATE UNIQUE INDEX uq_pickup_live_or_delivered ON pickups(claim_id)
  WHERE status IN ('Scheduled','PickedUp','Delivered');
CREATE INDEX ix_pickups_volunteer ON pickups(volunteer_id,status);
CREATE TABLE ratings (
  rating_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  claim_id bigint NOT NULL REFERENCES claims, rater_id bigint NOT NULL REFERENCES users,
  target_user_id bigint NOT NULL REFERENCES users,
  score smallint NOT NULL CHECK (score BETWEEN 1 AND 5), comments varchar(300),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK (rater_id<>target_user_id), UNIQUE(claim_id,rater_id,target_user_id)
);
CREATE INDEX ix_ratings_target ON ratings(target_user_id);
CREATE TABLE trust_ledger (
  ledger_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users, sequence bigint NOT NULL CHECK (sequence>0),
  action_type varchar(40) NOT NULL, ref_table varchar(40) NOT NULL, ref_id bigint NOT NULL,
  claim_id bigint REFERENCES claims, occurred_at timestamptz NOT NULL,
  payload jsonb NOT NULL, payload_version integer NOT NULL DEFAULT 1 CHECK (payload_version=1),
  prev_hash char(64) NOT NULL CHECK (prev_hash ~ '^[0-9a-f]{64}$'),
  curr_hash char(64) NOT NULL CHECK (curr_hash ~ '^[0-9a-f]{64}$'), UNIQUE(user_id,sequence)
);
CREATE INDEX ix_ledger_claim ON trust_ledger(claim_id);
CREATE TABLE notifications (
  notification_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users, event_id text NOT NULL,
  message varchar(200) NOT NULL, type varchar(30) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(), sent_at timestamptz, read_at timestamptz,
  UNIQUE(user_id,event_id)
);
CREATE INDEX ix_notifications_inbox ON notifications(user_id,read_at,created_at);
CREATE TABLE notification_outbox (
  outbox_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_id bigint NOT NULL REFERENCES notifications,
  channel varchar(10) NOT NULL CHECK (channel IN ('InApp','SMS','Push')),
  status varchar(12) NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending','Processing','Sent','Failed')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts>=0),
  next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp(), locked_until timestamptz,
  last_error text, UNIQUE(notification_id,channel)
);
CREATE INDEX ix_outbox_pending ON notification_outbox(status,next_attempt_at);
CREATE TABLE sessions (
  session_hash char(64) PRIMARY KEY CHECK (session_hash ~ '^[0-9a-f]{64}$'),
  user_id bigint NOT NULL REFERENCES users, created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  expires_at timestamptz NOT NULL, revoked_at timestamptz,
  CHECK (expires_at>created_at)
);
CREATE INDEX ix_sessions_user ON sessions(user_id);
CREATE TABLE idempotency_keys (
  actor_id bigint NOT NULL REFERENCES users, operation varchar(60) NOT NULL,
  key varchar(128) NOT NULL, request_hash char(64) NOT NULL,
  response_status integer NOT NULL, response_body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(), expires_at timestamptz NOT NULL,
  PRIMARY KEY(actor_id,operation,key), CHECK (expires_at>created_at)
);
CREATE TABLE seed_runs (
  seed_name text PRIMARY KEY, fixture_hash char(64) NOT NULL,
  anchor timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

-- Session lookup is private. Raw actor/zone GUCs are deliberately not authoritative.
CREATE FUNCTION dbthon_actor_id() RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT s.user_id FROM public.sessions s JOIN public.users u USING(user_id)
  WHERE s.session_hash=current_setting('app.session_hash',true)
    AND s.revoked_at IS NULL AND s.expires_at>statement_timestamp() AND u.active;
$$;
CREATE FUNCTION dbthon_actor_zone() RETURNS bigint LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT zone_id FROM public.users WHERE user_id=public.dbthon_actor_id();
$$;
CREATE FUNCTION dbthon_has_role(wanted text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT EXISTS(SELECT FROM public.users u JOIN public.user_roles r USING(user_id)
    WHERE u.user_id=public.dbthon_actor_id() AND u.active AND u.verified_status
      AND r.role=wanted AND r.approved_at IS NOT NULL);
$$;
CREATE FUNCTION dbthon_verified_actor() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT EXISTS(SELECT FROM public.users u JOIN public.user_roles r USING(user_id)
    WHERE u.user_id=public.dbthon_actor_id() AND u.active AND u.verified_status AND r.approved_at IS NOT NULL);
$$;
CREATE FUNCTION dbthon_zone_admin(wanted_zone bigint) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT public.dbthon_has_role('Admin') AND wanted_zone=public.dbthon_actor_zone();
$$;
CREATE FUNCTION dbthon_can_view_claim(wanted_claim bigint) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT EXISTS(SELECT FROM public.claims c JOIN public.food_listings l USING(listing_id)
    WHERE c.claim_id=wanted_claim AND l.zone_id=public.dbthon_actor_zone() AND (
      c.receiver_id=public.dbthon_actor_id() OR l.donor_id=public.dbthon_actor_id()
      OR public.dbthon_zone_admin(l.zone_id) OR EXISTS(SELECT FROM public.pickups p
        WHERE p.claim_id=c.claim_id AND p.volunteer_id=public.dbthon_actor_id())));
$$;

-- Canonical Unicode JSON: sorted normalized keys, compact UTF-8, integers only.
CREATE FUNCTION dbthon_canonical_json(value jsonb) RETURNS text LANGUAGE plpgsql IMMUTABLE
SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE kind text; result text;
BEGIN
  kind:=jsonb_typeof(value);
  IF kind='object' THEN
    IF EXISTS(SELECT FROM jsonb_object_keys(value) k WHERE k<>normalize(k,NFC)) THEN
      RAISE EXCEPTION 'NONCANONICAL_JSON_KEY';
    END IF;
    SELECT '{'||coalesce(string_agg(to_jsonb(key)::text||':'||public.dbthon_canonical_json(v),',' ORDER BY key COLLATE "C"),'')||'}'
      INTO result FROM jsonb_each(value) AS pairs(key,v);
    RETURN result;
  ELSIF kind='array' THEN
    SELECT '['||coalesce(string_agg(public.dbthon_canonical_json(v),',' ORDER BY ordinal),'')||']'
      INTO result FROM jsonb_array_elements(value) WITH ORDINALITY AS items(v,ordinal);
    RETURN result;
  ELSIF kind='string' THEN RETURN to_jsonb(normalize(value #>> '{}',NFC))::text;
  ELSIF kind='number' AND value::text !~ '^-?[0-9]+$' THEN RAISE EXCEPTION 'FLOAT_NOT_ALLOWED_IN_LEDGER';
  ELSE RETURN value::text;
  END IF;
END $$;
CREATE FUNCTION dbthon_record_event(affected bigint[], action text, reference_table text,
  reference_id bigint, related_claim bigint, body jsonb, event_time timestamptz DEFAULT clock_timestamp())
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE uid bigint; next_sequence bigint; previous text; envelope jsonb; event_hash text;
BEGIN
  -- All callers must acquire domain locks before this sorted user-lock set.
  PERFORM user_id FROM public.users WHERE user_id=ANY(affected) ORDER BY user_id FOR UPDATE;
  FOR uid IN SELECT DISTINCT unnest(affected) ORDER BY 1 LOOP
    SELECT sequence+1,curr_hash INTO next_sequence,previous FROM public.trust_ledger
      WHERE user_id=uid ORDER BY sequence DESC LIMIT 1;
    next_sequence:=coalesce(next_sequence,1); previous:=coalesce(previous,repeat('0',64));
    envelope:=jsonb_build_object('v',1,'user_id',uid,'sequence',next_sequence,
      'action_type',action,'ref_table',reference_table,'ref_id',reference_id,
      'claim_id',related_claim,'occurred_at',to_char(event_time AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.US"Z"'),
      'payload',body,'prev_hash',previous);
    event_hash:=encode(public.digest(convert_to(public.dbthon_canonical_json(envelope),'UTF8'),'sha256'),'hex');
    INSERT INTO public.trust_ledger(user_id,sequence,action_type,ref_table,ref_id,claim_id,occurred_at,payload,prev_hash,curr_hash)
      VALUES(uid,next_sequence,action,reference_table,reference_id,related_claim,event_time,body,previous,event_hash);
  END LOOP;
END $$;
CREATE FUNCTION dbthon_notify(affected bigint[], event text, notice_type text, notice text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE uid bigint; notification bigint;
BEGIN
  FOR uid IN SELECT DISTINCT unnest(affected) ORDER BY 1 LOOP
    INSERT INTO public.notifications(user_id,event_id,message,type) VALUES(uid,event,notice,notice_type)
      ON CONFLICT(user_id,event_id) DO NOTHING RETURNING notification_id INTO notification;
    IF notification IS NOT NULL THEN
      INSERT INTO public.notification_outbox(notification_id,channel) VALUES(notification,'InApp');
    END IF;
  END LOOP;
END $$;
CREATE FUNCTION dbthon_immutable_ledger() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'LEDGER_IS_APPEND_ONLY'; END $$;
CREATE TRIGGER guard_ledger_immutable BEFORE UPDATE OR DELETE ON trust_ledger
  FOR EACH ROW EXECUTE FUNCTION dbthon_immutable_ledger();
CREATE FUNCTION dbthon_listing_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(NEW.listing_id,NEW.donor_id,NEW.zone_id,NEW.created_at)
    IS DISTINCT FROM ROW(OLD.listing_id,OLD.donor_id,OLD.zone_id,OLD.created_at) THEN
    RAISE EXCEPTION 'IMMUTABLE_LISTING_OWNER'; END IF;
  IF OLD.status<>'Available' AND ROW(NEW.food_type,NEW.category,NEW.quantity_kg,NEW.prepared_at,
      NEW.expiry_window_start,NEW.expiry_window_end,NEW.pickup_lat,NEW.pickup_long)
    IS DISTINCT FROM ROW(OLD.food_type,OLD.category,OLD.quantity_kg,OLD.prepared_at,
      OLD.expiry_window_start,OLD.expiry_window_end,OLD.pickup_lat,OLD.pickup_long) THEN
    RAISE EXCEPTION 'ALLOCATED_LISTING_IS_IMMUTABLE';
  END IF;
  IF NEW.status<>OLD.status AND NOT (
    (OLD.status='Available' AND NEW.status IN ('Claimed','Expired','Cancelled')) OR
    (OLD.status='Claimed' AND NEW.status IN ('Available','PickedUp','Expired','Cancelled')) OR
    (OLD.status='PickedUp' AND NEW.status IN ('Delivered','Expired'))
  ) THEN RAISE EXCEPTION 'INVALID_LISTING_TRANSITION'; END IF;
  NEW.updated_at:=clock_timestamp(); RETURN NEW;
END $$;
CREATE TRIGGER guard_listing_update BEFORE UPDATE ON food_listings
  FOR EACH ROW EXECUTE FUNCTION dbthon_listing_guard();
CREATE FUNCTION dbthon_claim_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(NEW.claim_id,NEW.listing_id,NEW.receiver_id,NEW.claimed_at)
    IS DISTINCT FROM ROW(OLD.claim_id,OLD.listing_id,OLD.receiver_id,OLD.claimed_at) THEN
    RAISE EXCEPTION 'IMMUTABLE_CLAIM';
  END IF;
  IF NEW.status<>OLD.status AND NOT (OLD.status='Confirmed' AND NEW.status IN ('Cancelled','Expired','Completed')) THEN
    RAISE EXCEPTION 'INVALID_CLAIM_TRANSITION';
  END IF; RETURN NEW;
END $$;
CREATE TRIGGER guard_claim_update BEFORE UPDATE ON claims FOR EACH ROW EXECUTE FUNCTION dbthon_claim_guard();
CREATE FUNCTION dbthon_pickup_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF ROW(NEW.claim_id,NEW.pickup_id,NEW.volunteer_id) IS DISTINCT FROM ROW(OLD.claim_id,OLD.pickup_id,OLD.volunteer_id) THEN
    RAISE EXCEPTION 'IMMUTABLE_PICKUP';
  END IF;
  IF NEW.status<>OLD.status AND NOT ((OLD.status='Scheduled' AND NEW.status IN ('PickedUp','Missed','Cancelled'))
      OR (OLD.status='PickedUp' AND NEW.status IN ('Delivered','Failed'))) THEN RAISE EXCEPTION 'INVALID_PICKUP_TRANSITION'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER guard_pickup_update BEFORE UPDATE ON pickups FOR EACH ROW EXECUTE FUNCTION dbthon_pickup_guard();

CREATE FUNCTION dbthon_claim_listing(wanted_listing bigint) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; listing public.food_listings%ROWTYPE; receiver public.users%ROWTYPE;
  capacity numeric; claimed bigint; moment timestamptz;
BEGIN
  actor:=public.dbthon_actor_id();
  IF actor IS NULL OR NOT public.dbthon_has_role('Receiver') THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
  SELECT * INTO listing FROM public.food_listings WHERE listing_id=wanted_listing
    AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
  PERFORM user_id FROM public.users WHERE user_id=ANY(ARRAY[actor,listing.donor_id]) ORDER BY user_id FOR UPDATE;
  -- No transaction-start now(): another claimant may have held the lock until expiry.
  moment:=clock_timestamp();
  IF listing.expiry_window_end<=moment THEN RAISE EXCEPTION 'LISTING_EXPIRED'; END IF;
  IF listing.status<>'Available' THEN RAISE EXCEPTION 'LISTING_UNAVAILABLE'; END IF;
  IF listing.expiry_window_start>moment THEN RAISE EXCEPTION 'WINDOW_NOT_OPEN'; END IF;
  IF actor=listing.donor_id THEN RAISE EXCEPTION 'SELF_CLAIM_FORBIDDEN'; END IF;
  SELECT * INTO receiver FROM public.users WHERE user_id=actor;
  IF receiver.zone_id<>listing.zone_id OR NOT receiver.active OR NOT receiver.verified_status
    OR NOT public.dbthon_has_role('Receiver') OR NOT EXISTS(
      SELECT FROM public.sessions s WHERE s.session_hash=current_setting('app.session_hash',true)
        AND s.user_id=actor AND s.revoked_at IS NULL AND s.expires_at>moment) THEN
    RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
  IF NOT EXISTS(SELECT FROM public.users u JOIN public.user_roles r USING(user_id)
    WHERE u.user_id=listing.donor_id AND u.active AND u.verified_status AND r.role='Donor' AND r.approved_at IS NOT NULL) THEN
    RAISE EXCEPTION 'DONOR_UNAVAILABLE'; END IF;
  SELECT capacity_kg INTO capacity FROM public.receiver_profiles WHERE user_id=actor;
  IF capacity IS NULL OR capacity<listing.quantity_kg THEN RAISE EXCEPTION 'CAPACITY_INSUFFICIENT'; END IF;
  IF NOT public.ST_DWithin(listing.pickup_location,
      public.ST_SetSRID(public.ST_MakePoint(receiver.longitude::float8,receiver.latitude::float8),4326)::public.geography,5000) THEN
    RAISE EXCEPTION 'OUTSIDE_PICKUP_RADIUS'; END IF;
  INSERT INTO public.claims(listing_id,receiver_id,claimed_at) VALUES(wanted_listing,actor,moment) RETURNING claim_id INTO claimed;
  UPDATE public.food_listings SET status='Claimed' WHERE listing_id=wanted_listing;
  PERFORM public.dbthon_record_event(ARRAY[actor,listing.donor_id],'claim.confirmed','claims',claimed,claimed,
    jsonb_build_object('listing_id',wanted_listing,'receiver_id',actor,'quantity_kg',to_char(listing.quantity_kg,'FM99999990.00')),moment);
  PERFORM public.dbthon_notify(ARRAY[actor,listing.donor_id],'claim:'||claimed||':confirmed','ClaimConfirmed','A food listing has been claimed.');
  RETURN claimed;
END $$;

-- Deduplicate attempts before summing mass; keep zero-activity zones in results.
CREATE VIEW zone_impact_summary WITH (security_invoker=true) AS
WITH activity AS (
  SELECT c.listing_id, bool_or(p.actual_pickup_time IS NOT NULL) AS picked,
    bool_or(p.status='Delivered') AS delivered FROM claims c LEFT JOIN pickups p USING(claim_id) GROUP BY c.listing_id
)
SELECT z.zone_id,z.zone_name,z.city,count(l.listing_id) AS total_listings,
  coalesce(sum(l.quantity_kg) FILTER(WHERE a.picked),0)::numeric(12,2) AS picked_up_kg,
  coalesce(sum(l.quantity_kg) FILTER(WHERE a.delivered),0)::numeric(12,2) AS delivered_kg,
  (coalesce(sum(l.quantity_kg) FILTER(WHERE a.delivered),0)/0.4)::numeric(12,2) AS estimated_meals
FROM zones z LEFT JOIN food_listings l USING(zone_id) LEFT JOIN activity a USING(listing_id)
GROUP BY z.zone_id,z.zone_name,z.city;
CREATE VIEW user_trust_summary WITH (security_invoker=true) AS
SELECT u.user_id,count(r.rating_id) AS rating_count,avg(r.score)::numeric(4,2) AS average_score
FROM users u LEFT JOIN ratings r ON r.target_user_id=u.user_id GROUP BY u.user_id;
CREATE VIEW public_users WITH (security_invoker=true,security_barrier=true) AS
SELECT user_id,zone_id,name,verified_status,active FROM users;

-- No broad DML grants: runtime writes go through guarded, auditable domain routines.
GRANT SELECT ON zones TO dbthon_runtime;
GRANT SELECT(user_id,zone_id,name,email,phone,latitude,longitude,verified_status,active,created_at) ON users TO dbthon_runtime;
GRANT SELECT ON user_roles,receiver_profiles,food_listings,claims,pickups,ratings,trust_ledger,notifications,
  zone_impact_summary,user_trust_summary,public_users TO dbthon_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON zones,users,user_roles,receiver_profiles,food_listings,claims,pickups,ratings,
  trust_ledger,notifications,notification_outbox,sessions,idempotency_keys,seed_runs TO dbthon_guard;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO dbthon_guard;
-- Guard routines use a private NOLOGIN role to avoid recursive FORCE RLS policies.
DO $$ DECLARE fn record; BEGIN
  FOR fn IN SELECT oid::regprocedure AS signature FROM pg_proc WHERE pronamespace='public'::regnamespace AND proname LIKE 'dbthon_%' LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',fn.signature);
    EXECUTE format('ALTER FUNCTION %s OWNER TO dbthon_guard',fn.signature);
  END LOOP;
END $$;
GRANT EXECUTE ON FUNCTION dbthon_actor_id(),dbthon_actor_zone(),dbthon_has_role(text),dbthon_verified_actor(),
  dbthon_zone_admin(bigint),dbthon_can_view_claim(bigint),dbthon_claim_listing(bigint) TO dbthon_runtime;

ALTER TABLE users ENABLE ROW LEVEL SECURITY; ALTER TABLE users FORCE ROW LEVEL SECURITY;
CREATE POLICY users_scope ON users FOR SELECT TO dbthon_runtime USING (
  user_id=public.dbthon_actor_id() OR (zone_id=public.dbthon_actor_zone() AND (
    (verified_status AND active AND public.dbthon_verified_actor()) OR public.dbthon_zone_admin(zone_id))));
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY; ALTER TABLE user_roles FORCE ROW LEVEL SECURITY;
CREATE POLICY role_scope ON user_roles FOR SELECT TO dbthon_runtime USING (
  user_id=public.dbthon_actor_id() OR EXISTS(SELECT FROM public.users u WHERE u.user_id=user_roles.user_id));
ALTER TABLE receiver_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE receiver_profiles FORCE ROW LEVEL SECURITY;
CREATE POLICY capacity_scope ON receiver_profiles FOR SELECT TO dbthon_runtime USING (
  user_id=public.dbthon_actor_id() OR EXISTS(SELECT FROM public.users u WHERE u.user_id=receiver_profiles.user_id AND public.dbthon_zone_admin(u.zone_id)));
ALTER TABLE food_listings ENABLE ROW LEVEL SECURITY; ALTER TABLE food_listings FORCE ROW LEVEL SECURITY;
CREATE POLICY listing_scope ON food_listings FOR SELECT TO dbthon_runtime USING (
  zone_id=public.dbthon_actor_zone() AND public.dbthon_verified_actor());
ALTER TABLE claims ENABLE ROW LEVEL SECURITY; ALTER TABLE claims FORCE ROW LEVEL SECURITY;
CREATE POLICY claim_scope ON claims FOR SELECT TO dbthon_runtime USING (public.dbthon_can_view_claim(claim_id));
ALTER TABLE pickups ENABLE ROW LEVEL SECURITY; ALTER TABLE pickups FORCE ROW LEVEL SECURITY;
CREATE POLICY pickup_scope ON pickups FOR SELECT TO dbthon_runtime USING (public.dbthon_can_view_claim(claim_id));
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY; ALTER TABLE ratings FORCE ROW LEVEL SECURITY;
CREATE POLICY rating_scope ON ratings FOR SELECT TO dbthon_runtime USING (public.dbthon_can_view_claim(claim_id));
ALTER TABLE trust_ledger ENABLE ROW LEVEL SECURITY; ALTER TABLE trust_ledger FORCE ROW LEVEL SECURITY;
CREATE POLICY ledger_scope ON trust_ledger FOR SELECT TO dbthon_runtime USING (
  user_id=public.dbthon_actor_id() OR EXISTS(SELECT FROM public.users u WHERE u.user_id=trust_ledger.user_id AND public.dbthon_zone_admin(u.zone_id)));
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY; ALTER TABLE notifications FORCE ROW LEVEL SECURITY;
CREATE POLICY inbox_scope ON notifications FOR SELECT TO dbthon_runtime USING (user_id=public.dbthon_actor_id());
-- No runtime grants/policies for credential/session/idempotency/outbox/seed tables.
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY; ALTER TABLE idempotency_keys FORCE ROW LEVEL SECURITY;
ALTER TABLE notification_outbox ENABLE ROW LEVEL SECURITY; ALTER TABLE notification_outbox FORCE ROW LEVEL SECURITY;
ALTER TABLE seed_runs ENABLE ROW LEVEL SECURITY; ALTER TABLE seed_runs FORCE ROW LEVEL SECURITY;
