-- Extend the published foundation; never rewrite revision 0001.
ALTER TABLE sessions ADD COLUMN csrf_hash char(64) CHECK (csrf_hash ~ '^[0-9a-f]{64}$');
CREATE TABLE auth_rate_limits (
  bucket_hash char(64) PRIMARY KEY CHECK (bucket_hash ~ '^[0-9a-f]{64}$'),
  window_start timestamptz NOT NULL, attempts integer NOT NULL CHECK (attempts>0)
);
CREATE TABLE verification_reviews (
  review_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id bigint NOT NULL REFERENCES users,
  admin_id bigint NOT NULL REFERENCES users,
  verified boolean NOT NULL, approved_roles jsonb NOT NULL,
  reason varchar(300) NOT NULL CHECK (length(trim(reason))>=3),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX ix_reviews_target ON verification_reviews(target_user_id,created_at);
GRANT SELECT,INSERT,UPDATE,DELETE ON auth_rate_limits,verification_reviews TO dbthon_guard;
GRANT USAGE,SELECT ON SEQUENCE verification_reviews_review_id_seq TO dbthon_guard;
ALTER TABLE auth_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_rate_limits FORCE ROW LEVEL SECURITY;
ALTER TABLE verification_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE verification_reviews FORCE ROW LEVEL SECURITY;
GRANT SELECT ON verification_reviews TO dbthon_runtime;
CREATE POLICY review_scope ON verification_reviews FOR SELECT TO dbthon_runtime USING (
  target_user_id=public.dbthon_actor_id() OR EXISTS(SELECT FROM public.users u
    WHERE u.user_id=verification_reviews.target_user_id AND public.dbthon_zone_admin(u.zone_id)));
GRANT SELECT ON zones TO dbthon_auth;

-- Auth pool can look up one credential; runtime cannot execute this function.
CREATE FUNCTION dbthon_auth_credentials(wanted_email text)
RETURNS TABLE(user_id bigint,password_hash text,active boolean)
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT u.user_id,u.password_hash,u.active FROM public.users u WHERE u.email=wanted_email;
$$;
CREATE FUNCTION dbthon_auth_throttle(bucket text, maximum integer, window_seconds integer)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE amount integer; moment timestamptz:=clock_timestamp();
BEGIN
  IF bucket !~ '^[0-9a-f]{64}$' OR maximum NOT BETWEEN 1 AND 100 OR window_seconds NOT BETWEEN 1 AND 3600 THEN
    RAISE EXCEPTION 'INVALID_INPUT'; END IF;
  INSERT INTO public.auth_rate_limits(bucket_hash,window_start,attempts) VALUES(bucket,moment,1)
  ON CONFLICT(bucket_hash) DO UPDATE SET
    attempts=CASE WHEN auth_rate_limits.window_start<=moment-make_interval(secs=>window_seconds)
      THEN 1 ELSE auth_rate_limits.attempts+1 END,
    window_start=CASE WHEN auth_rate_limits.window_start<=moment-make_interval(secs=>window_seconds)
      THEN moment ELSE auth_rate_limits.window_start END RETURNING attempts INTO amount;
  RETURN amount<=maximum;
END $$;
CREATE FUNCTION dbthon_register(body jsonb, hashed_password text) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE uid bigint; wanted_roles text[]; role_name text;
BEGIN
  SELECT array_agg(value) INTO wanted_roles FROM jsonb_array_elements_text(body->'roles');
  IF coalesce(cardinality(wanted_roles),0) NOT BETWEEN 1 AND 3
    OR NOT wanted_roles<@ARRAY['Donor','Receiver','Volunteer']::text[]
    OR hashed_password NOT LIKE '$argon2id$%' THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
  IF 'Receiver'=ANY(wanted_roles) AND coalesce((body->>'capacity_kg')::numeric,0)<=0 THEN
    RAISE EXCEPTION 'CAPACITY_REQUIRED'; END IF;
  INSERT INTO public.users(zone_id,name,email,phone,password_hash,latitude,longitude)
  VALUES((body->>'zone_id')::bigint,body->>'name',body->>'email',body->>'phone',hashed_password,
    (body->>'latitude')::numeric,(body->>'longitude')::numeric) RETURNING user_id INTO uid;
  FOREACH role_name IN ARRAY wanted_roles LOOP
    INSERT INTO public.user_roles(user_id,role) VALUES(uid,role_name);
  END LOOP;
  IF 'Receiver'=ANY(wanted_roles) THEN
    INSERT INTO public.receiver_profiles(user_id,capacity_kg) VALUES(uid,(body->>'capacity_kg')::numeric);
  END IF;
  PERFORM public.dbthon_record_event(ARRAY[uid],'identity.registered','users',uid,NULL,
    jsonb_build_object('roles',to_jsonb(wanted_roles),'zone_id',(body->>'zone_id')::bigint));
  PERFORM public.dbthon_notify(ARRAY[uid],'registration:'||uid,'VerificationPending',
    'Your account is awaiting zone administrator verification.');
  RETURN uid;
END $$;
CREATE FUNCTION dbthon_issue_session(uid bigint, expected_password_hash text,
  new_session_hash text, new_csrf_hash text, old_session_hash text DEFAULT NULL,
  replacement_password_hash text DEFAULT NULL) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE identity public.users%ROWTYPE; moment timestamptz;
BEGIN
  SELECT * INTO identity FROM public.users WHERE user_id=uid FOR UPDATE;
  IF NOT FOUND OR NOT identity.active OR identity.password_hash<>expected_password_hash THEN
    RAISE EXCEPTION 'INVALID_CREDENTIALS'; END IF;
  IF new_session_hash !~ '^[0-9a-f]{64}$' OR new_csrf_hash !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'INVALID_INPUT'; END IF;
  moment:=clock_timestamp();
  IF replacement_password_hash IS NOT NULL THEN
    IF replacement_password_hash NOT LIKE '$argon2id$%' THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
    UPDATE public.users SET password_hash=replacement_password_hash WHERE user_id=uid;
  END IF;
  UPDATE public.sessions SET revoked_at=moment WHERE user_id=uid
    AND session_hash=old_session_hash AND revoked_at IS NULL;
  -- At most five concurrent sessions per identity, oldest active ones revoked.
  UPDATE public.sessions SET revoked_at=moment WHERE session_hash IN (
    SELECT session_hash FROM public.sessions WHERE user_id=uid AND revoked_at IS NULL
      AND expires_at>moment ORDER BY created_at DESC,session_hash OFFSET 4);
  INSERT INTO public.sessions(session_hash,user_id,csrf_hash,created_at,expires_at)
    VALUES(new_session_hash,uid,new_csrf_hash,moment,moment+interval '12 hours');
  PERFORM public.dbthon_record_event(ARRAY[uid],'auth.login','users',uid,NULL,'{}'::jsonb,moment);
END $$;

-- Call again after domain/user locks. No locks here, so multi-user commands retain
-- listing -> claim -> pickup -> sorted-users order without an early actor lock.
CREATE FUNCTION dbthon_require_actor(require_csrf boolean DEFAULT false) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE uid bigint; expected_csrf text;
BEGIN
  SELECT s.user_id,s.csrf_hash INTO uid,expected_csrf FROM public.sessions s JOIN public.users u USING(user_id)
  WHERE s.session_hash=current_setting('app.session_hash',true) AND s.revoked_at IS NULL
    AND s.expires_at>clock_timestamp() AND u.active;
  IF uid IS NULL THEN RAISE EXCEPTION 'UNAUTHENTICATED'; END IF;
  IF require_csrf AND (expected_csrf IS NULL OR
    expected_csrf IS DISTINCT FROM nullif(current_setting('app.csrf_hash',true),'')) THEN
    RAISE EXCEPTION 'CSRF_INVALID'; END IF;
  RETURN uid;
END $$;
CREATE FUNCTION dbthon_revoke_session() RETURNS void LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE uid bigint;
BEGIN
  uid:=public.dbthon_require_actor(true);
  PERFORM FROM public.users WHERE user_id=uid FOR UPDATE;
  PERFORM public.dbthon_require_actor(true);
  UPDATE public.sessions SET revoked_at=clock_timestamp()
    WHERE session_hash=current_setting('app.session_hash',true) AND user_id=uid;
  PERFORM public.dbthon_record_event(ARRAY[uid],'auth.logout','users',uid,NULL,'{}'::jsonb);
END $$;
CREATE FUNCTION dbthon_update_profile(body jsonb) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER
SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE uid bigint; changed jsonb;
BEGIN
  uid:=public.dbthon_require_actor(true);
  PERFORM FROM public.users WHERE user_id=uid FOR UPDATE;
  PERFORM public.dbthon_require_actor(true);
  IF body-'name'-'phone'-'latitude'-'longitude'-'capacity_kg'<>'{}'::jsonb THEN
    RAISE EXCEPTION 'INVALID_INPUT'; END IF;
  UPDATE public.users SET name=coalesce(body->>'name',name),phone=coalesce(body->>'phone',phone),
    latitude=coalesce((body->>'latitude')::numeric,latitude),
    longitude=coalesce((body->>'longitude')::numeric,longitude) WHERE user_id=uid;
  IF body ? 'capacity_kg' THEN
    IF NOT EXISTS(SELECT FROM public.user_roles WHERE user_id=uid AND role='Receiver') THEN
      RAISE EXCEPTION 'RECEIVER_ROLE_REQUIRED'; END IF;
    INSERT INTO public.receiver_profiles(user_id,capacity_kg) VALUES(uid,(body->>'capacity_kg')::numeric)
      ON CONFLICT(user_id) DO UPDATE SET capacity_kg=excluded.capacity_kg;
  END IF;
  SELECT coalesce(jsonb_agg(key ORDER BY key),'[]'::jsonb) INTO changed FROM jsonb_object_keys(body) AS item(key);
  PERFORM public.dbthon_record_event(ARRAY[uid],'identity.profile_updated','users',uid,NULL,
    jsonb_build_object('changed_fields',changed));
  PERFORM public.dbthon_notify(ARRAY[uid],'profile:'||public.gen_random_uuid(),'ProfileChanged','Your profile was updated.');
  RETURN uid;
END $$;
CREATE FUNCTION dbthon_verify_user(target bigint, approved_roles text[], is_verified boolean, review_reason text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; target_zone bigint; review bigint; moment timestamptz;
BEGIN
  actor:=public.dbthon_require_actor(true);
  IF NOT public.dbthon_has_role('Admin') THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
  SELECT zone_id INTO target_zone FROM public.users WHERE user_id=target;
  IF target_zone IS NULL OR target_zone<>public.dbthon_actor_zone() THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
  PERFORM user_id FROM public.users WHERE user_id=ANY(ARRAY[actor,target]) ORDER BY user_id FOR UPDATE;
  PERFORM public.dbthon_require_actor(true);
  IF NOT public.dbthon_zone_admin(target_zone) OR NOT EXISTS(
    SELECT FROM public.users WHERE user_id=target AND zone_id=target_zone) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
  IF NOT coalesce(approved_roles,ARRAY[]::text[])<@ARRAY['Donor','Receiver','Volunteer']::text[] THEN
    RAISE EXCEPTION 'INVALID_ROLE'; END IF;
  IF is_verified AND coalesce(cardinality(approved_roles),0)=0 THEN RAISE EXCEPTION 'ROLE_REQUIRED'; END IF;
  IF EXISTS(SELECT FROM unnest(approved_roles) role_name WHERE NOT EXISTS(
    SELECT FROM public.user_roles WHERE user_id=target AND role=role_name)) THEN
    RAISE EXCEPTION 'ROLE_NOT_REQUESTED'; END IF;
  IF 'Receiver'=ANY(approved_roles) AND NOT EXISTS(
    SELECT FROM public.receiver_profiles WHERE user_id=target AND capacity_kg>0) THEN
    RAISE EXCEPTION 'CAPACITY_REQUIRED'; END IF;
  moment:=clock_timestamp();
  UPDATE public.users SET verified_status=is_verified WHERE user_id=target;
  UPDATE public.user_roles SET
    approved_at=CASE WHEN is_verified AND role=ANY(approved_roles) THEN moment ELSE NULL END,
    approved_by=CASE WHEN is_verified AND role=ANY(approved_roles) THEN actor ELSE NULL END
    WHERE user_id=target AND (role<>'Admin' OR NOT is_verified);
  INSERT INTO public.verification_reviews(target_user_id,admin_id,verified,approved_roles,reason,created_at)
    VALUES(target,actor,is_verified,to_jsonb(coalesce(approved_roles,ARRAY[]::text[])),review_reason,moment)
    RETURNING review_id INTO review;
  PERFORM public.dbthon_record_event(ARRAY[actor,target],'identity.verification_changed',
    'verification_reviews',review,NULL,jsonb_build_object('actor_id',actor,'verified',is_verified,
      'roles',to_jsonb(coalesce(approved_roles,ARRAY[]::text[]))),moment);
  PERFORM public.dbthon_notify(ARRAY[actor,target],'verification:'||review,'VerificationChanged',
    'Account verification was updated by a zone administrator.');
  RETURN target;
END $$;

-- Protect the existing claim entry point with session + CSRF validation as well.
ALTER FUNCTION dbthon_claim_listing(bigint) RENAME TO dbthon_claim_listing_impl;
REVOKE ALL ON FUNCTION dbthon_claim_listing_impl(bigint) FROM dbthon_runtime,PUBLIC;
CREATE FUNCTION dbthon_claim_listing(wanted_listing bigint) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
  PERFORM public.dbthon_require_actor(true);
  RETURN public.dbthon_claim_listing_impl(wanted_listing);
END $$;

DO $$ DECLARE fn record; BEGIN
  FOR fn IN SELECT oid::regprocedure AS signature FROM pg_proc WHERE pronamespace='public'::regnamespace
    AND proname IN ('dbthon_auth_credentials','dbthon_auth_throttle','dbthon_register','dbthon_issue_session',
      'dbthon_require_actor','dbthon_revoke_session','dbthon_update_profile','dbthon_verify_user','dbthon_claim_listing') LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',fn.signature);
    EXECUTE format('ALTER FUNCTION %s OWNER TO dbthon_guard',fn.signature);
  END LOOP;
END $$;
GRANT EXECUTE ON FUNCTION dbthon_auth_credentials(text),dbthon_auth_throttle(text,integer,integer),
  dbthon_register(jsonb,text),dbthon_issue_session(bigint,text,text,text,text,text) TO dbthon_auth;
GRANT EXECUTE ON FUNCTION dbthon_require_actor(boolean),dbthon_revoke_session(),dbthon_update_profile(jsonb),
  dbthon_verify_user(bigint,text[],boolean,text),dbthon_claim_listing(bigint) TO dbthon_runtime;
