ALTER TABLE notifications ADD COLUMN hidden_at timestamptz;
CREATE TABLE notification_preferences (
  user_id bigint PRIMARY KEY REFERENCES users,
  sms_enabled boolean NOT NULL DEFAULT false,
  push_enabled boolean NOT NULL DEFAULT false,
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE hidden_listings (
  user_id bigint NOT NULL REFERENCES users,
  listing_id bigint NOT NULL REFERENCES food_listings,
  hidden_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  PRIMARY KEY(user_id,listing_id)
);
CREATE TABLE admin_grants (
  grant_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id bigint NOT NULL REFERENCES users,
  admin_id bigint NOT NULL REFERENCES users,
  reason varchar(300) NOT NULL CHECK (length(trim(reason))>=3),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

GRANT SELECT ON notification_preferences TO dbthon_runtime;
GRANT SELECT ON hidden_listings TO dbthon_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON notification_preferences,hidden_listings,admin_grants TO dbthon_guard;
GRANT USAGE,SELECT ON SEQUENCE admin_grants_grant_id_seq TO dbthon_guard;
CREATE POLICY guard_scope ON notification_preferences TO dbthon_guard USING (true) WITH CHECK (true);
CREATE POLICY guard_scope ON hidden_listings TO dbthon_guard USING (true) WITH CHECK (true);
CREATE POLICY guard_scope ON admin_grants TO dbthon_guard USING (true) WITH CHECK (true);
CREATE POLICY preferences_scope ON notification_preferences FOR SELECT TO dbthon_runtime
  USING (user_id=public.dbthon_actor_id());
CREATE POLICY hidden_listings_scope ON hidden_listings FOR SELECT TO dbthon_runtime
  USING (user_id=public.dbthon_actor_id());
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_preferences FORCE ROW LEVEL SECURITY;
ALTER TABLE hidden_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE hidden_listings FORCE ROW LEVEL SECURITY;
ALTER TABLE admin_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_grants FORCE ROW LEVEL SECURITY;

CREATE FUNCTION dbthon_save_notification_preferences(wants_sms boolean,wants_push boolean)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint;
BEGIN
  actor:=public.dbthon_require_actor(true);
  INSERT INTO public.notification_preferences(user_id,sms_enabled,push_enabled)
    VALUES(actor,wants_sms,wants_push)
  ON CONFLICT(user_id) DO UPDATE SET sms_enabled=excluded.sms_enabled,
    push_enabled=excluded.push_enabled,updated_at=clock_timestamp();
END $$;

CREATE FUNCTION dbthon_clear_inbox() RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; affected integer;
BEGIN
  actor:=public.dbthon_require_actor(true);
  UPDATE public.notifications SET hidden_at=clock_timestamp()
    WHERE user_id=actor AND hidden_at IS NULL;
  GET DIAGNOSTICS affected=ROW_COUNT;
  RETURN affected;
END $$;

CREATE FUNCTION dbthon_hide_cancelled_listing(wanted_listing bigint) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; target public.food_listings%ROWTYPE;
BEGIN
  actor:=public.dbthon_require_actor(true);
  SELECT * INTO target FROM public.food_listings WHERE listing_id=wanted_listing FOR UPDATE;
  IF NOT FOUND OR target.donor_id<>actor OR target.status<>'Cancelled' THEN
    RAISE EXCEPTION 'NOT_FOUND';
  END IF;
  INSERT INTO public.hidden_listings(user_id,listing_id) VALUES(actor,wanted_listing)
    ON CONFLICT(user_id,listing_id) DO NOTHING;
  RETURN true;
END $$;

CREATE FUNCTION dbthon_grant_admin(target bigint,grant_reason text) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; actor_user public.users%ROWTYPE; target_user public.users%ROWTYPE; moment timestamptz;
BEGIN
  actor:=public.dbthon_require_actor(true);
  IF target=actor OR length(trim(grant_reason)) NOT BETWEEN 3 AND 300 THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
  PERFORM user_id FROM public.users WHERE user_id IN (actor,target) ORDER BY user_id FOR UPDATE;
  PERFORM public.dbthon_require_actor(true);
  SELECT * INTO actor_user FROM public.users WHERE user_id=actor;
  SELECT * INTO target_user FROM public.users WHERE user_id=target;
  IF NOT actor_user.active OR NOT actor_user.verified_status
    OR NOT EXISTS(SELECT FROM public.user_roles WHERE user_id=actor AND role='Admin' AND approved_at IS NOT NULL) THEN
    RAISE EXCEPTION 'ADMIN_REQUIRED';
  END IF;
  IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
  IF NOT target_user.active OR target_user.zone_id<>actor_user.zone_id THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
  IF EXISTS(SELECT FROM public.user_roles WHERE user_id=target AND role='Admin' AND approved_at IS NOT NULL) THEN
    RAISE EXCEPTION 'ALREADY_ADMIN';
  END IF;
  moment:=clock_timestamp();
  UPDATE public.users SET verified_status=true WHERE user_id=target;
  INSERT INTO public.user_roles(user_id,role,approved_at,approved_by)
    VALUES(target,'Admin',moment,actor)
  ON CONFLICT(user_id,role) DO UPDATE SET approved_at=excluded.approved_at,approved_by=excluded.approved_by;
  INSERT INTO public.admin_grants(target_user_id,admin_id,reason) VALUES(target,actor,trim(grant_reason));
  PERFORM public.dbthon_record_event(ARRAY[actor,target],'identity.admin_granted','users',target,NULL,
    jsonb_build_object('admin_id',actor,'zone_id',target_user.zone_id,'reason',trim(grant_reason)),moment);
  PERFORM public.dbthon_notify(ARRAY[target],'admin-granted:'||target||':'||actor||':'||extract(epoch FROM moment),
    'AdminAccessGranted','A community administrator granted you administrator access.');
  RETURN target;
END $$;

DO $$ DECLARE fn record; BEGIN
  FOR fn IN SELECT oid::regprocedure AS signature FROM pg_proc WHERE pronamespace='public'::regnamespace
    AND proname IN ('dbthon_save_notification_preferences','dbthon_clear_inbox',
      'dbthon_hide_cancelled_listing','dbthon_grant_admin') LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',fn.signature);
    EXECUTE format('ALTER FUNCTION %s OWNER TO dbthon_guard',fn.signature);
  END LOOP;
END $$;
GRANT EXECUTE ON FUNCTION dbthon_save_notification_preferences(boolean,boolean),dbthon_clear_inbox(),
  dbthon_hide_cancelled_listing(bigint),dbthon_grant_admin(bigint,text) TO dbthon_runtime;
