-- Zone community needs, reviewed updates and versioned pickup agreements.
CREATE TABLE food_requests (
 request_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 receiver_id bigint NOT NULL REFERENCES users, zone_id bigint NOT NULL REFERENCES zones,
 food_type varchar(80) NOT NULL CHECK(length(trim(food_type))>0),
 category varchar(10) NOT NULL CHECK(category IN ('Veg','NonVeg')),
 quantity_kg numeric(8,2) NOT NULL CHECK(quantity_kg>0), needed_by timestamptz NOT NULL,
 note varchar(300) NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 closed_at timestamptz, close_reason varchar(300), CHECK(needed_by>created_at)
);
CREATE INDEX ix_requests_zone_deadline ON food_requests(zone_id,needed_by,request_id);
CREATE TABLE food_request_offers (
 offer_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 request_id bigint NOT NULL REFERENCES food_requests, listing_id bigint NOT NULL UNIQUE REFERENCES food_listings,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX ix_offers_request ON food_request_offers(request_id);
CREATE TABLE community_updates (
 update_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 zone_id bigint NOT NULL REFERENCES zones, author_id bigint NOT NULL REFERENCES users,
 kind varchar(20) NOT NULL CHECK(kind IN ('Announcement','PartnerResource')),
 title varchar(100) NOT NULL CHECK(length(trim(title))>0), body varchar(1500) NOT NULL CHECK(length(trim(body))>0),
 link varchar(500) CHECK(link IS NULL OR link ~ '^https://[^[:space:]]+$'),
 ends_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(), archived_at timestamptz,
 CHECK(ends_at>created_at)
);
CREATE INDEX ix_updates_zone ON community_updates(zone_id,update_id);
CREATE TABLE community_suggestions (
 suggestion_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 zone_id bigint NOT NULL REFERENCES zones, author_id bigint NOT NULL REFERENCES users,
 kind varchar(20) NOT NULL CHECK(kind IN ('Announcement','PartnerResource')),
 title varchar(100) NOT NULL CHECK(length(trim(title))>0), body varchar(1500) NOT NULL CHECK(length(trim(body))>0),
 link varchar(500) CHECK(link IS NULL OR link ~ '^https://[^[:space:]]+$'), ends_at timestamptz NOT NULL,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 status varchar(12) NOT NULL DEFAULT 'Pending' CHECK(status IN ('Pending','Published','Rejected')),
 reviewed_by bigint REFERENCES users, reviewed_at timestamptz, reason varchar(300),
 update_id bigint REFERENCES community_updates, CHECK(ends_at>created_at)
);
CREATE INDEX ix_suggestions_zone ON community_suggestions(zone_id,status,suggestion_id);
ALTER TABLE pickups ADD COLUMN schedule_version integer NOT NULL DEFAULT 1;
CREATE TABLE pickup_proposals (
 claim_id bigint NOT NULL, pickup_id bigint NOT NULL, version integer NOT NULL CHECK(version>0),
 scheduled_time timestamptz NOT NULL, proposed_by bigint NOT NULL REFERENCES users,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(claim_id,pickup_id,version),
 FOREIGN KEY(claim_id,pickup_id) REFERENCES pickups(claim_id,pickup_id)
);
CREATE TABLE pickup_confirmations (
 claim_id bigint NOT NULL, pickup_id bigint NOT NULL, version integer NOT NULL,
 user_id bigint NOT NULL REFERENCES users, confirmed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 PRIMARY KEY(claim_id,pickup_id,version,user_id),
 FOREIGN KEY(claim_id,pickup_id,version) REFERENCES pickup_proposals(claim_id,pickup_id,version)
);
-- Existing bookings remain agreed; only newly accepted tasks require confirmations.
INSERT INTO pickup_proposals(claim_id,pickup_id,version,scheduled_time,proposed_by,created_at)
 SELECT claim_id,pickup_id,1,scheduled_time,volunteer_id,accepted_at FROM pickups;
INSERT INTO pickup_confirmations(claim_id,pickup_id,version,user_id)
 SELECT p.claim_id,p.pickup_id,1,participant FROM pickups p JOIN claims c USING(claim_id)
 JOIN food_listings l USING(listing_id) CROSS JOIN LATERAL unnest(ARRAY[l.donor_id,c.receiver_id,p.volunteer_id]) participant;

DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['food_requests','food_request_offers','community_updates','community_suggestions','pickup_proposals','pickup_confirmations'] LOOP
 EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY',t);
 EXECUTE format('CREATE POLICY guard_scope ON %I TO dbthon_guard USING(true) WITH CHECK(true)',t);
 EXECUTE format('GRANT SELECT ON %I TO dbthon_runtime',t);
 EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON %I TO dbthon_guard',t);
 END LOOP;
END $$;
GRANT USAGE,SELECT ON SEQUENCE food_requests_request_id_seq,food_request_offers_offer_id_seq,
 community_updates_update_id_seq,community_suggestions_suggestion_id_seq TO dbthon_guard;
CREATE POLICY requests_read ON food_requests FOR SELECT TO dbthon_runtime
 USING(zone_id=dbthon_actor_zone() AND dbthon_verified_actor());
CREATE POLICY offers_read ON food_request_offers FOR SELECT TO dbthon_runtime
 USING(EXISTS(SELECT FROM food_requests r WHERE r.request_id=food_request_offers.request_id));
CREATE POLICY updates_read ON community_updates FOR SELECT TO dbthon_runtime
 USING(zone_id=dbthon_actor_zone() AND (dbthon_zone_admin(zone_id) OR (archived_at IS NULL AND ends_at>clock_timestamp())));
CREATE POLICY suggestions_read ON community_suggestions FOR SELECT TO dbthon_runtime
 USING(zone_id=dbthon_actor_zone() AND (author_id=dbthon_actor_id() OR dbthon_zone_admin(zone_id)));
CREATE POLICY proposals_read ON pickup_proposals FOR SELECT TO dbthon_runtime USING(dbthon_can_view_claim(claim_id));
CREATE POLICY confirmations_read ON pickup_confirmations FOR SELECT TO dbthon_runtime USING(dbthon_can_view_claim(claim_id));
GRANT CREATE ON SCHEMA public TO dbthon_guard;

CREATE FUNCTION dbthon_request_delivered(wanted bigint) RETURNS numeric
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT coalesce(sum(l.quantity_kg),0) FROM public.food_requests r
 LEFT JOIN public.food_request_offers o ON o.request_id=r.request_id
 LEFT JOIN public.food_listings l ON l.listing_id=o.listing_id
 LEFT JOIN public.claims c ON c.listing_id=l.listing_id AND c.receiver_id=r.receiver_id AND c.status='Completed'
 WHERE r.request_id=wanted AND r.zone_id=public.dbthon_actor_zone() AND public.dbthon_verified_actor()
 AND c.claim_id IS NOT NULL;
$$;

CREATE FUNCTION dbthon_request_status(wanted bigint) RETURNS text
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT CASE WHEN r.closed_at IS NOT NULL THEN 'Closed'
 WHEN coalesce((SELECT sum(l.quantity_kg) FROM public.food_request_offers o
 JOIN public.food_listings l USING(listing_id) JOIN public.claims c USING(listing_id)
 WHERE o.request_id=r.request_id AND c.receiver_id=r.receiver_id AND c.status='Completed'),0)>=r.quantity_kg THEN 'Fulfilled'
 WHEN r.needed_by<=clock_timestamp() THEN 'Expired' ELSE 'Open' END
 FROM public.food_requests r WHERE r.request_id=wanted AND r.zone_id=public.dbthon_actor_zone() AND public.dbthon_verified_actor();
$$;

CREATE FUNCTION dbthon_community_command(operation text, object_id bigint, body jsonb, request_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; moment timestamptz; op_key text; fingerprint text; result jsonb; cached public.idempotency_keys%ROWTYPE;
 r public.food_requests%ROWTYPE; l public.food_listings%ROWTYPE; s public.community_suggestions%ROWTYPE;
 u public.community_updates%ROWTYPE; affected bigint[]; recipients bigint[]; ref bigint; table_name text;
BEGIN
 actor:=public.dbthon_require_actor(true);
 IF operation NOT IN ('request.create','request.close','request.offer','update.create','update.archive','suggestion.create','suggestion.publish','suggestion.reject')
 OR request_key IS NULL OR length(request_key) NOT BETWEEN 8 AND 128 OR request_key !~ '^[A-Za-z0-9_.:-]+$'
 OR jsonb_typeof(body)<>'object' THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 IF NOT public.dbthon_verified_actor() THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation='request.create' AND NOT public.dbthon_has_role('Receiver') THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation='request.offer' AND NOT public.dbthon_has_role('Donor') THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation LIKE 'update.%' OR operation IN ('suggestion.publish','suggestion.reject') THEN
 IF NOT public.dbthon_has_role('Admin') THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF; END IF;
 op_key:=operation||':'||coalesce(object_id,0); fingerprint:=encode(public.digest(convert_to(body::text,'UTF8'),'sha256'),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended(actor||':'||op_key||':'||request_key,0));
 IF operation='request.offer' THEN
 SELECT * INTO l FROM public.food_listings WHERE listing_id=(body->>'listing_id')::bigint AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
 IF NOT FOUND OR l.donor_id<>actor THEN RAISE EXCEPTION 'NOT_FOUND'; END IF; END IF;
 IF operation IN ('request.offer','request.close') THEN
 SELECT * INTO r FROM public.food_requests WHERE request_id=object_id AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 IF operation='request.close' AND r.receiver_id<>actor AND NOT public.dbthon_zone_admin(r.zone_id) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 END IF;
 IF operation IN ('suggestion.publish','suggestion.reject') THEN
 SELECT * INTO s FROM public.community_suggestions WHERE suggestion_id=object_id AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF; END IF;
 IF operation='update.archive' THEN
 SELECT * INTO u FROM public.community_updates WHERE update_id=object_id AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF; END IF;
 affected:=array_remove(ARRAY[actor,r.receiver_id,s.author_id],NULL);
 PERFORM user_id FROM public.users WHERE user_id=ANY(affected) ORDER BY user_id FOR UPDATE;
 PERFORM public.dbthon_require_actor(true);
 IF NOT public.dbthon_verified_actor() THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation='request.create' AND NOT public.dbthon_has_role('Receiver') THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation='request.offer' AND NOT public.dbthon_has_role('Donor') THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF (operation LIKE 'update.%' OR operation IN ('suggestion.publish','suggestion.reject')) AND NOT public.dbthon_has_role('Admin') THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 moment:=clock_timestamp();
 SELECT * INTO cached FROM public.idempotency_keys i WHERE i.actor_id=actor AND i.operation=op_key AND i.key=request_key;
 IF FOUND THEN IF cached.request_hash<>fingerprint THEN RAISE EXCEPTION 'IDEMPOTENCY_CONFLICT'; END IF; RETURN cached.response_body; END IF;
 IF operation='request.create' THEN
 IF body-ARRAY['food_type','category','quantity_kg','needed_by','note']<>'{}'::jsonb OR (body->>'needed_by')::timestamptz<=moment THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 INSERT INTO public.food_requests(receiver_id,zone_id,food_type,category,quantity_kg,needed_by,note,created_at)
 VALUES(actor,public.dbthon_actor_zone(),trim(body->>'food_type'),body->>'category',(body->>'quantity_kg')::numeric,
 (body->>'needed_by')::timestamptz,coalesce(body->>'note',''),moment) RETURNING request_id INTO ref;
 table_name:='food_requests';
 ELSIF operation='request.close' THEN
 IF body-ARRAY['reason']<>'{}'::jsonb OR length(trim(coalesce(body->>'reason',''))) NOT BETWEEN 3 AND 300 THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 UPDATE public.food_requests SET closed_at=moment,close_reason=body->>'reason' WHERE request_id=object_id;
 ref:=object_id; table_name:='food_requests';
 ELSIF operation='request.offer' THEN
 IF body-ARRAY['listing_id']<>'{}'::jsonb THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 IF public.dbthon_request_status(r.request_id)<>'Open' THEN RAISE EXCEPTION 'REQUEST_CLOSED'; END IF;
 IF NOT EXISTS(SELECT FROM public.users rx JOIN public.user_roles rr USING(user_id) WHERE rx.user_id=r.receiver_id AND rx.active AND rx.verified_status AND rr.role='Receiver' AND rr.approved_at IS NOT NULL) THEN RAISE EXCEPTION 'REQUEST_CLOSED'; END IF;
 IF l.status<>'Available' OR l.expiry_window_start>moment OR l.expiry_window_end<=moment OR l.donor_id=r.receiver_id THEN RAISE EXCEPTION 'LISTING_UNAVAILABLE'; END IF;
 IF EXISTS(SELECT FROM public.food_request_offers WHERE listing_id=l.listing_id) THEN RAISE EXCEPTION 'OFFER_EXISTS'; END IF;
 INSERT INTO public.food_request_offers(request_id,listing_id) VALUES(r.request_id,l.listing_id) RETURNING offer_id INTO ref;
 table_name:='food_request_offers';
 ELSIF operation IN ('update.create','suggestion.create') THEN
 IF body-ARRAY['kind','title','body','link','ends_at']<>'{}'::jsonb OR (body->>'ends_at')::timestamptz<=moment THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 IF operation='update.create' THEN
 INSERT INTO public.community_updates(zone_id,author_id,kind,title,body,link,ends_at,created_at)
 VALUES(public.dbthon_actor_zone(),actor,body->>'kind',trim(body->>'title'),trim(body->>'body'),body->>'link',(body->>'ends_at')::timestamptz,moment) RETURNING update_id INTO ref;
 table_name:='community_updates';
 ELSE
 INSERT INTO public.community_suggestions(zone_id,author_id,kind,title,body,link,ends_at,created_at)
 VALUES(public.dbthon_actor_zone(),actor,body->>'kind',trim(body->>'title'),trim(body->>'body'),body->>'link',(body->>'ends_at')::timestamptz,moment) RETURNING suggestion_id INTO ref;
 SELECT array_agg(user_id) INTO recipients FROM public.users WHERE zone_id=public.dbthon_actor_zone() AND active AND verified_status AND EXISTS(SELECT FROM public.user_roles rr WHERE rr.user_id=users.user_id AND rr.role='Admin' AND rr.approved_at IS NOT NULL);
 table_name:='community_suggestions'; END IF;
 ELSIF operation='suggestion.publish' THEN
 IF body<>'{}'::jsonb THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 IF s.status<>'Pending' OR s.ends_at<=moment THEN RAISE EXCEPTION 'ACTION_NOT_ALLOWED'; END IF;
 INSERT INTO public.community_updates(zone_id,author_id,kind,title,body,link,ends_at)
 VALUES(s.zone_id,actor,s.kind,s.title,s.body,s.link,s.ends_at) RETURNING update_id INTO ref;
 UPDATE public.community_suggestions SET status='Published',reviewed_by=actor,reviewed_at=moment,update_id=ref WHERE suggestion_id=s.suggestion_id;
 table_name:='community_updates';
 ELSIF operation='suggestion.reject' THEN
 IF body-ARRAY['reason']<>'{}'::jsonb OR length(trim(coalesce(body->>'reason',''))) NOT BETWEEN 3 AND 300 THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 IF s.status<>'Pending' THEN RAISE EXCEPTION 'ACTION_NOT_ALLOWED'; END IF;
 UPDATE public.community_suggestions SET status='Rejected',reviewed_by=actor,reviewed_at=moment,reason=$3->>'reason' WHERE suggestion_id=s.suggestion_id;
 ref:=object_id; table_name:='community_suggestions';
 ELSE
 IF body<>'{}'::jsonb THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 UPDATE public.community_updates SET archived_at=moment WHERE update_id=object_id;
 ref:=object_id; table_name:='community_updates';
 END IF;
 IF operation IN ('update.create','suggestion.publish') THEN
 SELECT array_agg(user_id) INTO recipients FROM public.users WHERE active AND zone_id=public.dbthon_actor_zone(); END IF;
 PERFORM public.dbthon_record_event(affected,operation,table_name,ref,NULL,jsonb_build_object('zone_id',public.dbthon_actor_zone()),moment);
 PERFORM public.dbthon_notify(coalesce(recipients,affected),op_key||':'||request_key,'CommunityUpdate',
 CASE WHEN operation='request.offer' THEN 'A donor offered a listing for your food request. Open Food requests to view it.'
 WHEN operation IN ('update.create','suggestion.publish') THEN 'A community update was published. Open Community updates to read it.'
 WHEN operation='suggestion.create' THEN 'A community suggestion is awaiting administrator review.'
 ELSE 'Your community request or suggestion was updated.' END);
 result:=jsonb_build_object('data',jsonb_build_object('id',ref));
 INSERT INTO public.idempotency_keys(actor_id,operation,key,request_hash,response_status,response_body,created_at,expires_at)
 VALUES(actor,op_key,request_key,fingerprint,200,result,moment,moment+interval '24 hours');
 RETURN result;
END $$;

CREATE FUNCTION dbthon_schedule_command(wanted_claim bigint, wanted_pickup bigint, body jsonb, request_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; l public.food_listings%ROWTYPE; c public.claims%ROWTYPE; p public.pickups%ROWTYPE;
 required bigint[]; cached public.idempotency_keys%ROWTYPE; op_key text; fingerprint text; moment timestamptz; result jsonb;
BEGIN
 actor:=public.dbthon_require_actor(true);
 IF request_key IS NULL OR length(request_key) NOT BETWEEN 8 AND 128 OR request_key !~ '^[A-Za-z0-9_.:-]+$'
 OR jsonb_typeof(body)<>'object' OR body-ARRAY['version','scheduled_time']<>'{}'::jsonb THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 SELECT * INTO l FROM public.food_listings WHERE listing_id=(SELECT listing_id FROM public.claims WHERE claim_id=wanted_claim) AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 SELECT * INTO c FROM public.claims WHERE claim_id=wanted_claim FOR UPDATE;
 SELECT * INTO p FROM public.pickups WHERE claim_id=wanted_claim AND pickup_id=wanted_pickup FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 required:=ARRAY[l.donor_id,c.receiver_id,p.volunteer_id];
 IF actor<>ALL(required) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 PERFORM user_id FROM public.users WHERE user_id=ANY(required) ORDER BY user_id FOR UPDATE;
 PERFORM public.dbthon_require_actor(true);
 IF NOT public.dbthon_has_role(CASE WHEN actor=l.donor_id THEN 'Donor' WHEN actor=c.receiver_id THEN 'Receiver' ELSE 'Volunteer' END) THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 op_key:='schedule:'||wanted_claim||':'||wanted_pickup;
 fingerprint:=encode(public.digest(convert_to(body::text,'UTF8'),'sha256'),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended(actor||':'||op_key||':'||request_key,0));
 SELECT * INTO cached FROM public.idempotency_keys i WHERE i.actor_id=actor AND i.operation=op_key AND i.key=request_key;
 IF FOUND THEN IF cached.request_hash<>fingerprint THEN RAISE EXCEPTION 'IDEMPOTENCY_CONFLICT'; END IF; RETURN cached.response_body; END IF;
 moment:=clock_timestamp();
 IF c.status<>'Confirmed' OR p.status<>'Scheduled' OR l.expiry_window_end<=moment OR p.scheduled_time+interval '15 minutes'<=moment THEN RAISE EXCEPTION 'ACTION_NOT_ALLOWED'; END IF;
 IF (body->>'version')::integer IS DISTINCT FROM p.schedule_version THEN RAISE EXCEPTION 'STALE_PROPOSAL'; END IF;
 IF body ? 'scheduled_time' THEN
 IF (body->>'scheduled_time')::timestamptz<=moment OR (body->>'scheduled_time')::timestamptz<l.expiry_window_start OR (body->>'scheduled_time')::timestamptz>=l.expiry_window_end THEN RAISE EXCEPTION 'INVALID_WINDOW'; END IF;
 UPDATE public.pickups SET scheduled_time=(body->>'scheduled_time')::timestamptz,schedule_version=schedule_version+1 WHERE claim_id=wanted_claim AND pickup_id=wanted_pickup RETURNING * INTO p;
 INSERT INTO public.pickup_proposals(claim_id,pickup_id,version,scheduled_time,proposed_by) VALUES(wanted_claim,wanted_pickup,p.schedule_version,p.scheduled_time,actor);
 END IF;
 INSERT INTO public.pickup_confirmations(claim_id,pickup_id,version,user_id) VALUES(wanted_claim,wanted_pickup,p.schedule_version,actor) ON CONFLICT DO NOTHING;
 PERFORM public.dbthon_record_event(required,CASE WHEN body ? 'scheduled_time' THEN 'schedule.proposed' ELSE 'schedule.confirmed' END,'pickups',wanted_pickup,wanted_claim,jsonb_build_object('version',p.schedule_version,'scheduled_time',p.scheduled_time),moment);
 PERFORM public.dbthon_notify(required,op_key||':'||request_key,'StatusUpdate','A pickup time was proposed or confirmed. Open the exchange to review agreements.');
 result:=jsonb_build_object('data',jsonb_build_object('id',wanted_pickup));
 INSERT INTO public.idempotency_keys(actor_id,operation,key,request_hash,response_status,response_body,created_at,expires_at) VALUES(actor,op_key,request_key,fingerprint,200,result,moment,moment+interval '24 hours');
 RETURN result;
END $$;

-- Keep the original legal transitions, with a booking agreement gate before collection.
ALTER FUNCTION dbthon_command(text,bigint,bigint,jsonb,text) RENAME TO dbthon_command_0005;
REVOKE ALL ON FUNCTION dbthon_command_0005(text,bigint,bigint,jsonb,text) FROM dbthon_runtime;
CREATE FUNCTION dbthon_command(operation text, object_id bigint, attempt_id bigint, body jsonb, request_key text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE result jsonb; l public.food_listings%ROWTYPE; p public.pickups%ROWTYPE; participant bigint; cid bigint; pid bigint;
BEGIN
 PERFORM public.dbthon_require_actor(true);
 IF operation='pickup.collect' THEN
 SELECT * INTO l FROM public.food_listings WHERE listing_id=(SELECT listing_id FROM public.claims WHERE claim_id=object_id) AND zone_id=public.dbthon_actor_zone() FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 SELECT * INTO p FROM public.pickups WHERE claim_id=object_id AND pickup_id=attempt_id;
 IF NOT FOUND OR p.volunteer_id<>public.dbthon_actor_id() THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 IF NOT public.dbthon_has_role('Volunteer') THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF NOT EXISTS(SELECT FROM public.idempotency_keys i WHERE i.actor_id=public.dbthon_actor_id() AND i.operation='pickup.collect:'||object_id||':'||attempt_id AND i.key=request_key) AND
 (SELECT count(*) FROM public.pickup_confirmations pc WHERE pc.claim_id=object_id AND pc.pickup_id=attempt_id AND pc.version=p.schedule_version)<>3 THEN RAISE EXCEPTION 'SCHEDULE_UNCONFIRMED'; END IF;
 END IF;
 result:=public.dbthon_command_0005(operation,object_id,attempt_id,body,request_key);
 IF operation='pickup.accept' THEN
 cid:=(result->'data'->>'claim_id')::bigint; pid:=(result->'data'->>'pickup_id')::bigint;
 SELECT * INTO p FROM public.pickups WHERE claim_id=cid AND pickup_id=pid;
 IF NOT EXISTS(SELECT FROM public.pickup_proposals WHERE claim_id=cid AND pickup_id=pid) THEN
 INSERT INTO public.pickup_proposals(claim_id,pickup_id,version,scheduled_time,proposed_by) VALUES(cid,pid,1,p.scheduled_time,p.volunteer_id);
 INSERT INTO public.pickup_confirmations(claim_id,pickup_id,version,user_id) VALUES(cid,pid,1,p.volunteer_id);
 END IF;
 END IF;
 RETURN result;
END $$;
DO $$ DECLARE fn regprocedure; BEGIN
 FOREACH fn IN ARRAY ARRAY['dbthon_request_delivered(bigint)'::regprocedure,'dbthon_request_status(bigint)'::regprocedure,'dbthon_community_command(text,bigint,jsonb,text)'::regprocedure,'dbthon_schedule_command(bigint,bigint,jsonb,text)'::regprocedure,'dbthon_command(text,bigint,bigint,jsonb,text)'::regprocedure] LOOP
 EXECUTE format('ALTER FUNCTION %s OWNER TO dbthon_guard',fn);
 EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',fn);
 EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO dbthon_runtime',fn);
 END LOOP;
END $$;
REVOKE CREATE ON SCHEMA public FROM dbthon_guard;
