-- Saved discovery, private exchange coordination and auditable issue review.
CREATE TABLE saved_listings (
 user_id bigint NOT NULL REFERENCES users, listing_id bigint NOT NULL REFERENCES food_listings,
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY(user_id,listing_id)
);
CREATE TABLE exchange_messages (
 message_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 claim_id bigint NOT NULL REFERENCES claims, sender_id bigint NOT NULL REFERENCES users,
 recipient_ids bigint[] NOT NULL, body varchar(1000) NOT NULL CHECK(length(trim(body)) BETWEEN 1 AND 1000),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX ix_messages_claim ON exchange_messages(claim_id,message_id);
CREATE INDEX ix_messages_sender_time ON exchange_messages(sender_id,created_at);
CREATE TABLE community_issues (
 issue_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reporter_id bigint NOT NULL REFERENCES users, zone_id bigint NOT NULL REFERENCES zones,
 listing_id bigint NOT NULL REFERENCES food_listings, claim_id bigint REFERENCES claims,
 message_id bigint REFERENCES exchange_messages,
 category text NOT NULL CHECK(category IN('FoodSafety','NoShow','MisleadingListing','AbusiveMessage','Other')),
 detail varchar(1000) NOT NULL CHECK(length(trim(detail)) BETWEEN 3 AND 1000),
 status text NOT NULL DEFAULT 'Open' CHECK(status IN('Open','Reviewing','Resolved','Dismissed')),
 created_at timestamptz NOT NULL DEFAULT clock_timestamp(), reviewed_at timestamptz,
 reviewed_by bigint REFERENCES users, review_note varchar(500)
);
CREATE INDEX ix_issues_zone_status ON community_issues(zone_id,status,issue_id);
CREATE INDEX ix_issues_reporter_time ON community_issues(reporter_id,created_at);
CREATE UNIQUE INDEX uq_issue_open_target ON community_issues(reporter_id,listing_id,coalesce(claim_id,0),coalesce(message_id,0))
 WHERE status IN('Open','Reviewing');
GRANT SELECT ON saved_listings,exchange_messages,community_issues TO dbthon_runtime;
GRANT SELECT,INSERT,UPDATE,DELETE ON saved_listings,exchange_messages,community_issues TO dbthon_guard;
GRANT USAGE,SELECT ON SEQUENCE exchange_messages_message_id_seq,community_issues_issue_id_seq TO dbthon_guard;

CREATE FUNCTION dbthon_chat_participant(wanted_claim bigint) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT public.dbthon_verified_actor() AND EXISTS(
 SELECT FROM public.claims c JOIN public.food_listings l USING(listing_id)
 WHERE c.claim_id=wanted_claim AND l.zone_id=public.dbthon_actor_zone() AND (
 (l.donor_id=public.dbthon_actor_id() AND public.dbthon_has_role('Donor')) OR
 (c.receiver_id=public.dbthon_actor_id() AND public.dbthon_has_role('Receiver')) OR
 (public.dbthon_has_role('Volunteer') AND public.dbthon_actor_id()=(
   SELECT p.volunteer_id FROM public.pickups p WHERE p.claim_id=c.claim_id
   AND p.pickup_id=(SELECT max(p2.pickup_id) FROM public.pickups p2 WHERE p2.claim_id=c.claim_id)
   AND p.status IN('Scheduled','PickedUp','Delivered')))));
$$;
ALTER FUNCTION dbthon_chat_participant(bigint) OWNER TO dbthon_guard;
REVOKE ALL ON FUNCTION dbthon_chat_participant(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION dbthon_chat_participant(bigint) TO dbthon_runtime;

ALTER TABLE saved_listings ENABLE ROW LEVEL SECURITY; ALTER TABLE saved_listings FORCE ROW LEVEL SECURITY;
ALTER TABLE exchange_messages ENABLE ROW LEVEL SECURITY; ALTER TABLE exchange_messages FORCE ROW LEVEL SECURITY;
ALTER TABLE community_issues ENABLE ROW LEVEL SECURITY; ALTER TABLE community_issues FORCE ROW LEVEL SECURITY;
CREATE POLICY guard_scope ON saved_listings TO dbthon_guard USING(true) WITH CHECK(true);
CREATE POLICY guard_scope ON exchange_messages TO dbthon_guard USING(true) WITH CHECK(true);
CREATE POLICY guard_scope ON community_issues TO dbthon_guard USING(true) WITH CHECK(true);
CREATE POLICY saved_scope ON saved_listings FOR SELECT TO dbthon_runtime USING(user_id=public.dbthon_actor_id() AND public.dbthon_verified_actor());
CREATE POLICY message_scope ON exchange_messages FOR SELECT TO dbthon_runtime USING(
 public.dbthon_chat_participant(claim_id) AND (sender_id=public.dbthon_actor_id() OR public.dbthon_actor_id()=ANY(recipient_ids)));
CREATE POLICY issue_scope ON community_issues FOR SELECT TO dbthon_runtime USING(
 public.dbthon_verified_actor() AND ((reporter_id=public.dbthon_actor_id() AND zone_id=public.dbthon_actor_zone()) OR public.dbthon_zone_admin(zone_id)));

CREATE FUNCTION dbthon_experience_command(operation text,wanted_id bigint,body jsonb,request_key text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; fingerprint text; op_key text; cached public.idempotency_keys%ROWTYPE;
 l public.food_listings%ROWTYPE; c public.claims%ROWTYPE; p public.pickups%ROWTYPE;
 issue public.community_issues%ROWTYPE; affected bigint[]; result jsonb; ref_id bigint;
 supplied_message public.exchange_messages%ROWTYPE; moment timestamptz;
BEGIN
 actor:=public.dbthon_require_actor(true);
 IF NOT public.dbthon_verified_actor() THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation NOT IN('bookmark.save','bookmark.remove','message.send','issue.open','issue.review')
 OR request_key IS NULL OR length(request_key) NOT BETWEEN 8 AND 128 OR request_key !~ '^[A-Za-z0-9_.:-]+$'
 OR jsonb_typeof(body)<>'object' THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 op_key:=operation||':'||wanted_id;
 fingerprint:=encode(public.digest(convert_to(body::text,'UTF8'),'sha256'),'hex');
 PERFORM pg_advisory_xact_lock(hashtextextended(actor||':'||op_key||':'||request_key,0));
 IF operation='message.send' THEN
   SELECT listing_id INTO ref_id FROM public.claims WHERE claim_id=wanted_id;
 ELSIF operation='issue.review' THEN
   SELECT listing_id INTO ref_id FROM public.community_issues WHERE issue_id=wanted_id;
 ELSE ref_id:=wanted_id; END IF;
 SELECT * INTO l FROM public.food_listings WHERE listing_id=ref_id AND
 (zone_id=public.dbthon_actor_zone() OR (operation='issue.review' AND public.dbthon_zone_admin(zone_id))) FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 affected:=ARRAY[actor];
 IF operation='message.send' THEN
   SELECT * INTO c FROM public.claims WHERE claim_id=wanted_id FOR UPDATE;
   SELECT * INTO p FROM public.pickups WHERE claim_id=wanted_id ORDER BY pickup_id DESC LIMIT 1 FOR UPDATE;
   IF NOT public.dbthon_chat_participant(wanted_id) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
   affected:=ARRAY[l.donor_id,c.receiver_id];
   IF p.status IN('Scheduled','PickedUp') THEN affected:=array_append(affected,p.volunteer_id); END IF;
 ELSIF operation='issue.review' THEN
   SELECT * INTO issue FROM public.community_issues WHERE issue_id=wanted_id FOR UPDATE;
   IF NOT public.dbthon_zone_admin(issue.zone_id) OR actor=issue.reporter_id THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
   affected:=ARRAY[actor,issue.reporter_id];
 END IF;
 PERFORM user_id FROM public.users WHERE user_id=ANY(affected) ORDER BY user_id FOR UPDATE;
 PERFORM public.dbthon_require_actor(true);
 IF NOT public.dbthon_verified_actor() THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF operation='message.send' AND NOT public.dbthon_chat_participant(wanted_id) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
 IF operation='issue.review' AND NOT public.dbthon_zone_admin(issue.zone_id) THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 SELECT * INTO cached FROM public.idempotency_keys i WHERE i.actor_id=actor AND i.operation=op_key AND i.key=request_key;
 IF FOUND THEN
   IF cached.request_hash<>fingerprint THEN RAISE EXCEPTION 'IDEMPOTENCY_CONFLICT'; END IF;
   RETURN cached.response_body;
 END IF;
 moment:=clock_timestamp();
 IF operation IN('bookmark.save','bookmark.remove') THEN
   IF body<>'{}' THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
   IF operation='bookmark.save' THEN
     DELETE FROM public.saved_listings s USING public.food_listings old
       WHERE s.user_id=actor AND s.listing_id=old.listing_id AND
       (old.zone_id<>public.dbthon_actor_zone() OR old.status NOT IN('Available','Claimed') OR old.expiry_window_end<=moment);
     IF l.status NOT IN('Available','Claimed') OR l.expiry_window_end<=moment THEN RAISE EXCEPTION 'LISTING_UNAVAILABLE'; END IF;
     IF (SELECT count(*) FROM public.saved_listings WHERE user_id=actor)>=100 AND NOT EXISTS(
       SELECT FROM public.saved_listings WHERE user_id=actor AND listing_id=wanted_id) THEN RAISE EXCEPTION 'SAVE_LIMIT'; END IF;
     INSERT INTO public.saved_listings(user_id,listing_id) VALUES(actor,wanted_id) ON CONFLICT DO NOTHING;
   ELSE DELETE FROM public.saved_listings WHERE user_id=actor AND listing_id=wanted_id; END IF;
   result:=jsonb_build_object('data',jsonb_build_object('id',wanted_id));
   PERFORM public.dbthon_record_event(ARRAY[actor],operation,'food_listings',wanted_id,NULL,'{}');
 ELSIF operation='message.send' THEN
   IF body-ARRAY['body']<>'{}' OR body->>'body' IS NULL OR length(trim(body->>'body')) NOT BETWEEN 1 AND 1000 THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
   IF c.status<>'Confirmed' OR l.status NOT IN('Claimed','PickedUp') OR l.expiry_window_end<=moment THEN RAISE EXCEPTION 'ACTION_NOT_ALLOWED'; END IF;
   IF (SELECT count(*) FROM public.exchange_messages WHERE sender_id=actor AND created_at>moment-interval '10 minutes')>=20 THEN RAISE EXCEPTION 'RATE_LIMITED'; END IF;
   INSERT INTO public.exchange_messages(claim_id,sender_id,recipient_ids,body)
   VALUES(wanted_id,actor,affected,trim(body->>'body')) RETURNING message_id INTO ref_id;
   result:=jsonb_build_object('data',jsonb_build_object('id',ref_id));
   PERFORM public.dbthon_record_event(affected,'exchange.message_sent','exchange_messages',ref_id,wanted_id,jsonb_build_object('claim_id',wanted_id));
   -- Never put the private message body in a ledger or external alert.
   PERFORM public.dbthon_notify(ARRAY(SELECT unnest(affected) EXCEPT SELECT actor),'message:'||ref_id,'ExchangeMessage','A participant sent a message in exchange #'||wanted_id||'. Open the exchange to read it.');
 ELSIF operation='issue.open' THEN
   IF body-ARRAY['category','detail','claim_id','message_id']<>'{}' OR body->>'category' NOT IN('FoodSafety','NoShow','MisleadingListing','AbusiveMessage','Other')
   OR body->>'category' IS NULL OR body->>'detail' IS NULL OR length(trim(body->>'detail')) NOT BETWEEN 3 AND 1000 THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
   IF body->>'claim_id' IS NOT NULL THEN
     SELECT * INTO c FROM public.claims WHERE claim_id=(body->>'claim_id')::bigint AND listing_id=l.listing_id;
     IF NOT FOUND OR NOT public.dbthon_can_view_claim(c.claim_id) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
   END IF;
   IF body->>'message_id' IS NOT NULL THEN
     SELECT * INTO supplied_message FROM public.exchange_messages WHERE message_id=(body->>'message_id')::bigint;
     IF NOT FOUND OR supplied_message.claim_id IS DISTINCT FROM c.claim_id OR NOT public.dbthon_chat_participant(c.claim_id)
     OR NOT (supplied_message.sender_id=actor OR actor=ANY(supplied_message.recipient_ids)) THEN RAISE EXCEPTION 'NOT_FOUND'; END IF;
   END IF;
   IF body->>'category'='AbusiveMessage' AND supplied_message.message_id IS NULL THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
   IF (SELECT count(*) FROM public.community_issues WHERE reporter_id=actor AND created_at>moment-interval '1 day')>=5 THEN RAISE EXCEPTION 'RATE_LIMITED'; END IF;
   IF EXISTS(SELECT FROM public.community_issues WHERE reporter_id=actor AND listing_id=wanted_id
   AND coalesce(claim_id,0)=coalesce(c.claim_id,0) AND coalesce(message_id,0)=coalesce(supplied_message.message_id,0) AND status IN('Open','Reviewing')) THEN RAISE EXCEPTION 'ISSUE_EXISTS'; END IF;
   INSERT INTO public.community_issues(reporter_id,zone_id,listing_id,claim_id,message_id,category,detail)
   VALUES(actor,l.zone_id,wanted_id,c.claim_id,supplied_message.message_id,body->>'category',trim(body->>'detail')) RETURNING issue_id INTO ref_id;
   result:=jsonb_build_object('data',jsonb_build_object('id',ref_id));
   PERFORM public.dbthon_record_event(ARRAY[actor],'issue.opened','community_issues',ref_id,c.claim_id,jsonb_build_object('listing_id',wanted_id,'category',body->>'category'));
   PERFORM public.dbthon_notify(ARRAY(SELECT u.user_id FROM public.users u JOIN public.user_roles r USING(user_id)
     WHERE (u.zone_id=l.zone_id OR u.email='z1.admin@example.invalid') AND u.active AND u.verified_status AND r.role='Admin' AND r.approved_at IS NOT NULL),
     'issue:'||ref_id,'IssueReported','A community member submitted report #'||ref_id||'. Open issue review to inspect it.');
 ELSIF operation='issue.review' THEN
   IF body-ARRAY['status','note']<>'{}' OR body->>'status' NOT IN('Reviewing','Resolved','Dismissed') OR body->>'status' IS NULL
   OR body->>'note' IS NULL OR length(trim(body->>'note')) NOT BETWEEN 3 AND 500 THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
   IF issue.status IN('Resolved','Dismissed') THEN RAISE EXCEPTION 'ACTION_NOT_ALLOWED'; END IF;
   UPDATE public.community_issues SET status=body->>'status',review_note=trim(body->>'note'),reviewed_at=moment,reviewed_by=actor WHERE issue_id=wanted_id;
   result:=jsonb_build_object('data',jsonb_build_object('id',wanted_id));
   PERFORM public.dbthon_record_event(affected,'issue.reviewed','community_issues',wanted_id,issue.claim_id,jsonb_build_object('status',body->>'status'));
   PERFORM public.dbthon_notify(ARRAY[issue.reporter_id],'issue-review:'||wanted_id||':'||request_key,'IssueReviewed','An administrator updated report #'||wanted_id||'. Open your reports to see the result.');
 END IF;
 INSERT INTO public.idempotency_keys(actor_id,operation,key,request_hash,response_status,response_body,created_at,expires_at)
 VALUES(actor,op_key,request_key,fingerprint,200,result,moment,moment+interval '24 hours');
 RETURN result;
END $$;
ALTER FUNCTION dbthon_experience_command(text,bigint,jsonb,text) OWNER TO dbthon_guard;
REVOKE ALL ON FUNCTION dbthon_experience_command(text,bigint,jsonb,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION dbthon_experience_command(text,bigint,jsonb,text) TO dbthon_runtime;

-- Only the message explicitly attached to a report may cross the admin boundary.
CREATE FUNCTION dbthon_reported_message(wanted_issue bigint) RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT jsonb_build_object('body',m.body,'created_at',m.created_at)
 FROM public.community_issues i JOIN public.exchange_messages m USING(message_id)
 WHERE i.issue_id=wanted_issue AND public.dbthon_verified_actor() AND (
   public.dbthon_zone_admin(i.zone_id) OR
   (i.reporter_id=public.dbthon_actor_id() AND i.zone_id=public.dbthon_actor_zone()));
$$;
ALTER FUNCTION dbthon_reported_message(bigint) OWNER TO dbthon_guard;
REVOKE ALL ON FUNCTION dbthon_reported_message(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION dbthon_reported_message(bigint) TO dbthon_runtime;

CREATE FUNCTION dbthon_personal_impact(begins timestamptz,ends timestamptz) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor bigint; result jsonb;
BEGIN
 actor:=public.dbthon_require_actor(false);
 IF NOT public.dbthon_verified_actor() THEN RAISE EXCEPTION 'VERIFICATION_REQUIRED'; END IF;
 IF begins IS NULL OR ends IS NULL OR begins>=ends OR ends-begins>interval '366 days' THEN RAISE EXCEPTION 'INVALID_INPUT'; END IF;
 WITH involvement AS (
   SELECT l.listing_id,l.quantity_kg,l.donor_id=actor AS donated,c.receiver_id=actor AS received,
    p.volunteer_id=actor AS transported,p.actual_pickup_time,p.delivery_time
   FROM public.food_listings l JOIN public.claims c USING(listing_id) JOIN public.pickups p USING(claim_id)
   WHERE l.zone_id=public.dbthon_actor_zone() AND
    (l.donor_id=actor OR c.receiver_id=actor OR p.volunteer_id=actor)
 ), picked AS (
   SELECT DISTINCT listing_id,quantity_kg FROM involvement WHERE actual_pickup_time>=begins AND actual_pickup_time<ends
 ), delivered AS (
   SELECT listing_id,max(quantity_kg) AS kg,bool_or(donated) AS donated,
    bool_or(received) AS received,bool_or(transported) AS transported FROM involvement
   WHERE delivery_time>=begins AND delivery_time<ends GROUP BY listing_id
 ) SELECT jsonb_build_object(
   'picked_up_kg',coalesce((SELECT sum(quantity_kg) FROM picked),0)::text,
   'delivered_kg',coalesce(sum(kg),0)::text,'delivered_exchanges',count(*),
   'donated_kg',coalesce(sum(kg) FILTER(WHERE donated),0)::text,
   'received_kg',coalesce(sum(kg) FILTER(WHERE received),0)::text,
   'transported_kg',coalesce(sum(kg) FILTER(WHERE transported),0)::text,
   'estimated_meals',floor(coalesce(sum(kg),0)/0.4),
   'includes_demo_data',EXISTS(SELECT FROM public.seed_runs),
   'period_start',begins,'period_end',ends) INTO result FROM delivered;
 RETURN result;
END $$;
ALTER FUNCTION dbthon_personal_impact(timestamptz,timestamptz) OWNER TO dbthon_guard;
REVOKE ALL ON FUNCTION dbthon_personal_impact(timestamptz,timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION dbthon_personal_impact(timestamptz,timestamptz) TO dbthon_runtime;
